#call error headers
Success = 0
STOCK_CSV_DBASE_FILE_NOT_EXIST = 1
STOCK_OPT_EXPDATE_DOES_NOT_EXIST = 2
STOCK_OPT_STPRICE_DOES_NOT_EXIST = 3
STOCK_OPT_VOL_DOES_NOT_EXIST = 4
STOCK_OPEN_INT_UNAVAILABLE = 5
STOCK_OPT_PRICE_UNAVAILABLE = 6
STOCK_OPT_VOLUME_UNAVAILABLE = 7
DATE_DOESNOT_EXIST_IN_STOCK_CSV_DATA_FILE = 8
STOCK_UNKNOWN = 9
STOCK_OPEN_INT_NOT_GREATERTHAN_THRESOLD_SET = 10
STOCK_OPEN_INT_ZERO = 11
STOCK_OPT_PRICE_LESSTHAN_MARGIN_VALVE_SET = 12
STOCK_OPEN_INT_NO_CHANGE_IN_PERCENTAGE = 13
STOCK_OPT_VOL_OI_OV_DIFF_NOT_GREATERTHAN_PERCENTAGE_SET = 14
OPT_EXP_DATE_IS_INCORRECT = 15
STOCK_VOL_UNAVAILABLE = 16
STOCK_PRICE_UNAVAILABLE = 17
STOCK_OPENINT_PRICE_OPTPRICE_UNAVAILABLE =18
OI_PERCENTAGE_JUMP_OUTPUT_DOESNOT_CREATED = 19
LOCAL_CSV_FILE_DOESNOT_EXIST = 20

#logging headers
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
debug = 0
info = 0

